# rpc_url = "https://api.mainnet-beta.solana.com"
rpc_url = "https://devnet.helius-rpc.com/?api-key=71d05d9f-5d94-4548-9137-c6c3d9f69b3e"
key_path = "/Users/andrecorreia/.config/solana/id.json"
min_crank_fee = 1000001